### PR TITLE
Create Proj3ReidWatters.md

### LINKED ISSUE #19: Project 3 for Julia Watters
new file for project 3

### PR DESCRIPTION
**Pull request by ReidWatters**
Issue Completed

Closes #19

### CODE REVIEW

**Review by dmr8230 — APPROVED** [review]
looks good

**Comment by cwl8528** [comment]
Reviewed

**Review by cwl8528 — COMMENTED** [review]
https://github.com/douglaskline/trucktrackrepo/pull/38

**Review by cwl8528 — APPROVED** [review]
Reviewed

**Review by AzriAH — APPROVED** [review]
Solid

**Pull request merged**
