### PR TITLE
Issue 7 scaffold initial application

### LINKED ISSUE #7: scaffold initial application
[ ] overall solution
[ ] data access layer
[ ] database
[ ] ui

### PR DESCRIPTION
**Pull request by douglaskline**
closes #7

### CODE REVIEW

**Review by ReidWatters — COMMENTED** [review]
👍

**Review by dmr8230 — COMMENTED** [review]
looks good

**Review by billtnguyen — APPROVED** [review]

**Review by cwl8528 — APPROVED** [review]
Reviewed

**Review by Kishawna — APPROVED** [review]
changes approved

**Pull request merged**
