### PR TITLE
Create Proj3afm6921.md

### LINKED ISSUE #21: Project 3 for Alaina Mitchell

### PR DESCRIPTION
**Pull request by alainamitchell**
issue completed
closes #21

### CODE REVIEW

**Review by douglaskline — APPROVED** [review]
ok, this looks a little sketchy but it might work
💯

**Review by robertrieger — APPROVED** [review]
Looks good

**Review by Chrishensley98 — COMMENTED** [review]
This looks good!

**Review by Chrishensley98 — COMMENTED** [review]
This looks good!

**Pull request merged**
