### PR TITLE
Create Proj3billtnguyen.md

### LINKED ISSUE #24: Project 3 for Bill Nguyen

### PR DESCRIPTION
**Pull request by billtnguyen**
Issue Completed
closes #24

### CODE REVIEW

**Review by ReidWatters — APPROVED** [review]

**Comment by Chrishensley98** [comment]
This looks good. Well done!

**Review by ReidWatters — COMMENTED** [review]
👍

**Comment by AzriAH** [comment]
Solid

**Review by alainamitchell — APPROVED** [review]

**Review by AzriAH — APPROVED** [review]
Nice Work

**Review by Chrishensley98 — COMMENTED** [review]
This looks good!

**Pull request merged**
