### PR TITLE
Proj 9 - Removed timestamp from Details view

### PR DESCRIPTION
**Pull request by yopinq**
removed timestamp from Details view

### CODE REVIEW

**Comment by dmr8230** [comment]
great job!

**Review by dmr8230 — APPROVED** [review]

**Comment by douglaskline** [comment]
closes issue #207

**Review by Kishawna — COMMENTED** [review]
Looks like all of the correct timestamps are removed

**Review by Kishawna — APPROVED** [review]
Looks like all of the correct timestamps are removed

**Pull request merged**
