### PR TITLE
Create Proj3yopinq.md

### PR DESCRIPTION
**Pull request by yopinq**
Project 3 issue completed

### CODE REVIEW

**Comment by zacharyserfling** [comment]
Reviewed

**Review by zacharyserfling — COMMENTED** [review]
Reviewed

**Review by zacharyserfling — COMMENTED** [review]
Reviewed

**Comment by noah-vu** [comment]
Review Project 4

**Review by noah-vu — APPROVED** [review]

**Review by alainamitchell — APPROVED** [review]

**Review by zacharyserfling — APPROVED** [review]

**Pull request merged**
